services:
    _defaults:
        autowire: true
        autoconfigure: false

    SymfonyProcessManager\Command\ServeCommand:
        tags: ['console.command']

    SymfonyProcessManager\Command\Serve\WorkerProcessFactoryInterface: '@SymfonyProcessManager\Command\Serve\WorkerProcessFactory'
    SymfonyProcessManager\Command\Serve\WorkerProcessFactory: ~
    SymfonyProcessManager\Command\Serve\WorkerOutputFormatter: ~
    SymfonyProcessManager\Command\Serve\WorkerOutputHandler: ~
    SymfonyProcessManager\Command\Serve\HttpServer: ~
    SymfonyProcessManager\Metrics\MetricsRegistry: ~
