services:
    _defaults:
        autowire: true
        autoconfigure: false

    SymfonyProcessManager\Command\ServeCommand:
        tags: ['console.command']

    SymfonyProcessManager\Worker\WorkerProcessFactoryInterface: '@SymfonyProcessManager\Worker\WorkerProcessFactory'
    SymfonyProcessManager\Worker\WorkerProcessFactory: ~
    SymfonyProcessManager\Output\WorkerOutputFormatter: ~
    SymfonyProcessManager\Output\WorkerOutputHandler: ~
    SymfonyProcessManager\Ipc\IpcCodec: ~
    SymfonyProcessManager\Http\HttpServer: ~

    SymfonyProcessManager\Metrics\PrometheusRendererInterface: '@SymfonyProcessManager\Metrics\PrometheusTextRenderer'
    SymfonyProcessManager\Metrics\PrometheusTextRenderer: ~

    SymfonyProcessManager\Metrics\MetricFactoryInterface: '@SymfonyProcessManager\Metrics\MetricFactory'
    SymfonyProcessManager\Metrics\MetricFactory: ~
    SymfonyProcessManager\Metrics\MetricsRegistry: ~
    SymfonyProcessManager\ProcessManager\ProcessManagerLoop: ~
